spring:
  application:
    name: user-authentication-mgt-appl
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:rogate
    username: system
    password: Changeme0
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
server:
  port: 8080
  address: 0.0.0.0
logging:
  level:
    org.springframework.security.web: info
    root: info
  file:
    name: build/log/${spring.application.name}.log
jwt:
  secret: 'thebigbrownfoxjumpsoverthelazydog'
